
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from reportlab.lib import colors

from reportlab.platypus.tables import (
    Table,
    TableStyle
)

from datetime import datetime

# =========================================
# PREMIUM PDF REPORT
# =========================================

def generate_pdf(

    prediction,

    confidence

):

    doc = SimpleDocTemplate(

        "AI_Report.pdf"
    )

    styles = getSampleStyleSheet()

    content = []

    # =========================================
    # TITLE
    # =========================================

    title = Paragraph(

        "AI Document Intelligence Report",

        styles['Title']
    )

    content.append(title)

    content.append(Spacer(1, 20))

    # =========================================
    # TIMESTAMP
    # =========================================

    current_time = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    timestamp = Paragraph(

        f"<b>Generated On:</b> {current_time}",

        styles['BodyText']
    )

    content.append(timestamp)

    content.append(Spacer(1, 20))

    # =========================================
    # SUMMARY TABLE
    # =========================================

    data = [

        ["Metric", "Value"],

        ["Prediction", prediction],

        ["Confidence", f"{confidence:.2f}%"],

        ["AI Engine", "BERT + NLP"],

        ["Status", "Analysis Complete"]
    ]

    table = Table(data, colWidths=[200, 250])

    table.setStyle(TableStyle([

        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#2563EB")),

        ('TEXTCOLOR', (0,0), (-1,0), colors.white),

        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),

        ('BOTTOMPADDING', (0,0), (-1,0), 12),

        ('BACKGROUND', (0,1), (-1,-1), colors.whitesmoke),

        ('GRID', (0,0), (-1,-1), 1, colors.grey),

        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),

    ]))

    content.append(table)

    content.append(Spacer(1, 30))

    # =========================================
    # AI INSIGHTS
    # =========================================

    insights_title = Paragraph(

        "AI Insights",

        styles['Heading2']
    )

    content.append(insights_title)

    content.append(Spacer(1, 10))

    insights = Paragraph(

        """
        This document was analyzed using advanced
        NLP and transformer-based AI models.
        The platform identified document patterns,
        classification confidence and semantic
        structure successfully.
        """,

        styles['BodyText']
    )

    content.append(insights)

    content.append(Spacer(1, 20))

    # =========================================
    # RECOMMENDATIONS
    # =========================================

    recommendations_title = Paragraph(

        "Recommendations",

        styles['Heading2']
    )

    content.append(recommendations_title)

    content.append(Spacer(1, 10))

    recommendations = Paragraph(

        """
        • Continue improving document quality.<br/>
        • Maintain structured formatting.<br/>
        • Use AI analytics for deeper insights.<br/>
        • Leverage chatbot assistance for Q&A.
        """,

        styles['BodyText']
    )

    content.append(recommendations)

    content.append(Spacer(1, 30))

    # =========================================
    # FOOTER
    # =========================================

    footer = Paragraph(

        """
        <i>
        Generated by AI Document Intelligence Platform
        </i>
        """,

        styles['BodyText']
    )

    content.append(footer)

    # =========================================
    # BUILD PDF
    # =========================================

    doc.build(content)

